### ISSUE TITLE
Add Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-baratheon#14]
## User Story
As a user, I should be able to add messages by clicking enter.

## AC
**Given** A user navigates to your page
**Then** they type in the input field
**And** when they hit enter a new message should be created
**And** the message should show up in the new chat window

## Dev Notes
* Create a new file called javascripts/components/eventListeners.js
* In this file, create a new event listener function called `eventListeners`
  * Add an import statement for chatbox.js (import chatBox from chatBox.js)
  *  add an event listener that listens to `chatInput` and calls `chatBox.newMessageEvent` on keyup event 
* In chatBox.js, create a new function called `newMessageEvent` with an event parameter
  *  this function will contain an if statement to check if the e.keyCode === 13.
    * IF TRUE
      1. Create a variable called `messageContent` and assign `e.target.value` to it. 
      2. Prevent default
      3. Run `messageBuilder(messageContent)`
  * add `newMessageEvent` to the export statement of chatBox.js
* Create a global variable called `messageIterator`.
* Create the messageBuilder function that contains one parameter:  `messageToPrint`
  * This function will create a new object called `newMessage`. This object will be added to the global `messages` array. `newMessage` will contain the following:
    1. messageId: `message${messageIterator}` (this is the global variable you created a few steps ago)
    2. userId: 'user1'
    3. name: 'Me'
    4. timestamp: `${moment().format('MMMM D, YYYY h:mm A'}`
    5. messageContent: `${messageToPrint}`
  * Using the push array method, add `newMessage` to the global `messages` array
  * Run chatBoxBuilder()
  * messageIterator = messageIterator + 1

**Comment by bobbybaxter** [comment]
Possible way to add to .json file:
https://stackoverflow.com/questions/18884840/adding-a-new-array-element-to-a-json-object
