### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-baratheon#16]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
* On eventListeners.js, in the eventListener() function, create a new eventListener: 
```javascript
$('#largeText').change(() => {
  if($(this).is(':checked')) {
    $('body').addClass('largeText');
  } else {
    $('body').removeClass('largeText');
  }
});
```
* In `main.scss`, create a css class largeText that changes the font-size to 2rem.

**Comment by Lakiajo** [comment]
$('#increaseSize').click(function increaseSize() {
    let size = parseInt($('#chatBox').css('font-size'), 10);
    if ($(this).is(':checked')) {
      size += 4;
    } else {
      size -= 4;
      if (size <= 10) {
        size = 10;
      }
    }
    $('#chatBox').css('font-size', size);
  });
