### ISSUE TITLE
Delete Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-baratheon#17]
## User Story
As a user I should be able to delete messages.

If you are doing multiple users you should only be able to delete **your** messages

## AC
**Given** A message on your page
**Then** there should be a delete button for each message
**And** when the button is pushed the message should no longer exist

## Dev Notes
* If not already added, add an import statement import chatBox from chatBox.js
* Add the following event listener to the javascripts/components/eventListeners.js file: `$('body').on('click', 'delete', chatBox.deleteMessage);`
* In chatBox.js, build the deleteMessage function with an event parameter:
  * Reference the function commented below for a nearly exact copy of what we need this function to look like. 
  * In words, this function will loop through the array of messages and find the message to be deleted.
  * At the end of deleteMessage, be sure to run chatBoxBuilder();
  * Add `eventListeners` to the export statement.

**Comment by bobbybaxter** [comment]
delete splicing reference: 
```
const deleteFunction = (e) => {
  const buttonId = e.target.id;
  ingredients.forEach((ingredient, index) => {
    if(ingredient.id === buttonId) {
      ingredients.splice(index, 1);
    };
  });
  domStringBuilder(ingredients);
  addDeleteEvents();
};
```
```javascript
const deleteMessage = (e) => {
  const buttonId = e.target.id;
  $.each(messages, (message, index) => {
    if(message.messageId === buttonId) {
      messages.splice(index, 1);
    };
  });
  chatBoxBuilder();
};
```

**Comment by Lakiajo** [comment]
const deleteMessage = (e) => {
  e.preventDefault();
  const messageId = $(e.target).closest('.messageContainer').attr('id');
  messages.forEach((message, index) => {
    if (message.messageId === messageId) {
      messages.splice(index, 1);
    }
  });
  chatBoxBuilder();
};
