### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-baratheon#18]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `db/messages.json`

## Dev Notes
* In the `index.html` file, create a `<div>` element with an id of `chatBox`
* In `javascript/helpers`, create a new directory called `data`
* In `javascript/helpers/data`, create a `messagesData.js`
* `messagesData.js` will export a variable containing an axios call to .get messages.json
* In `javascript/components`, create a new directory called `chatBox.js`
* `chatBox.js` should import json data from `messagesData.js` and printToDom from `util.js`
* `chatBox.js` should contain two functions: initializeMessages, chatBoxBuilder and a global variable called `messages`
  * initializeMessage - Reference the comments below to find the code snippet needed for this function.
  * chatBoxBuilder -  This function will build a domstring by forEach through the global `messages` array. The domstring will create a new `<div>` for each message containing the message timestamp and message content and an X button to delete the message (reference comments for code snippet). The overall message `<div>` should have an id equal to the messageId found in each message object. Add the userId key as a class to each message `<div>`. The domstring will lastly be passed through printToDom to print it to the `chatBox` div
* export `chatBoxBuilder()` and import to main.js so that it can run in the init() function.

**Comment by bobbybaxter** [comment]
reference on how we previously wrote `initializeMessages`:
```const initializeMovies = () => {
  moviesData.getMoviesData()
    .then((resp) => {
      const movieResults = resp.data.movies;
      movies = movieResults;
      domStringBuilder();
      moviesEventListeners.addClickHandlers();
    })
    .catch(err => console.error(err));
};
```
**Do this in JQuery**!  Here's a reference: https://api.jquery.com/promise/

Delete button: 
```
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
```
