### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-baratheon#2]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
* Create a `nav` element at the top of the index.html page
* In the class list of the `nav` element, add `sticky-top` to the list
* Reference the below comments for code snippets to build the logo, input, and clear button in the navbar
* The `input` element should have an id of `chatInput` and the clear button should have an id of `clearChat`

**Comment by bobbybaxter** [comment]
![Screen Shot 2019-04-27 at 11 44 29 AM](https://user-images.githubusercontent.com/5022594/56852499-e0cd6c00-68e1-11e9-8b12-6476368de749.png)

**Comment by bobbybaxter** [comment]
Navbar Brand (logo):
```
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap
  </a>
</nav>
```

Input and button Bootstrap:
```
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
```
