### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-baratheon#3]
## User Story
As a user, with sensitive eyes, I should be able to chat using a dark theme.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Dark Theme"
**And** they should be able to click this checkbox
**And** when the checkbox is selected the page should show a dark theme with lightly colored text

## Dev Notes
* On eventListeners.js, in the eventListener() function, create a new eventListener: 
```javascript
$('#darkTheme').change(() => {
  if($(this).is(':checked')) {
    $('body').addClass('darkTheme');
  } else {
    $('body').removeClass('darkTheme');
  }
});
```
* In `main.scss`, create a class called darkTheme that changes background-color to black and color to white

**Comment by Lakiajo** [comment]
$('#toggleDark').click(() => {
    $('#content').toggleClass('darkMode');
  });
