### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-baratheon#5]
## User Story
As a user, I should be able to edit a message then save my new message.

## AC
**WHEN** I add a message
**Then** I see an edit button on the message in the chatbox
**And** when the button is clicked, the edit button changes to a save button
**And** the message text is editable
**And** when the save button is clicked, the save button changes to an edit button
**And** the text is saved

## Dev
* In `chatBoxBuilder()` in chatBox.js, add an editing image/symbol (probably font-awesome) and a saving image/symbol before the delete button in the domString. the editing button should have a class of 'edit'. Additionally, add a save button that should have a class of 'save' and "style="display: none;"
* In eventListeners.js, in the eventListeners() function, add two event listeners:
  *`$(.edit).on('click', util.editMessage);`
  *`$(.save).on('click', util.saveMessage);`
* In util.js, build two functions called editMessage and saveMessage, both with event parameters
  * editMessage - hides the edit button, adds the class 'editable' to the message div, adds attribute ('contenteditable', 'true'), shows '.save' *see example code below*
  * saveMessage - hides the save button, removes the class 'editable' from the message div, removes attribute 'contenteditable', shows '.edit'. *see example code below*,  then splices the original messageContent from within the global `messages` array object and adds in the newly edited messageContent.

**Comment by bobbybaxter** [comment]
original instructions (for recordkeeping): 
1. Let users edit an existing message. Add an edit button next to the delete button that, when clicked, will take the message and put it back in the message input at the top.
1. Once user edits the message and presses the return key again, the message text in the list should be updated.

**Comment by bobbybaxter** [comment]
edit and save button templates:
```javascript
$('.edit').click(function(){
  $(this).hide();
  $('.box').addClass('editable');
  $('.text').attr('contenteditable', 'true');  
  $('.save').show();
});

$('.save').click(function(){
  $(this).hide();
  $('.box').removeClass('editable');
  $('.text').removeAttr('contenteditable');
  $('.edit').show();
});
```
