### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-baratheon#9]
## User Story
As a user, using all the chatting sites, I always see clean looking timestamps.

**Dirty Timestamp:**  2014-09-08T08:02:17-05:00
**Clean Timestamp:**  September 8, 2014 8:02 PM

## AC
**Given** A user navigates to your page
**Then** they see all the messages
**And**  the messages should have nice looking timestamps

## Dev Notes
* Real JS developers hate dates - they use a magical library called [MomentJS](https://momentjs.com/)
```js
npm install moment --save
```

**Comment by bobbybaxter** [comment]
closed issue because this has been rolled into other tickets
